name: DroneWorld
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Mount backend code
      - ./config/projct-key.json:/app/.gcp/project-key.json  # Mount the specific key file
      - ./config/airsim:/root/Documents/AirSim  # Mount the AirSim folder
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.gcp/projct-key.json
    network_mode: "host"  # Use the host network for direct communication

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Mount frontend code for live editing
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necessary for live-reload in Docker
    depends_on:
      - backend