name: DroneWorld
services:
  backend:
    image: droneworld/droneworld-backend:v1.0.0
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Mount backend code
      - ./config/airsim:/root/Documents/AirSim  # Mount the AirSim folder
    # depends_on:
    #   - DRV-Unreal

  frontend:
    image: droneworld/droneworld-frontend:v1.0.0
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Mount frontend code for live editing
      - /app/node_modules # Separate node_modules to avoid host overwrite
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necessary for live-reload in Docker
    depends_on:
      - backend