name: DroneWorld
services:
  backend:
    build:
      context: .  # Set the project root as the build context for backend
      dockerfile: ./backend/Dockerfile  # Specify the Dockerfile location for backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:C:/app  # Mount backend code for live editing
      - ./config/settings.json:C:/Documents/AirSim/settings.json  # Mount settings.json for simulation

  frontend:
    build:
      context: .  # Set the project root as the build context for frontend
      dockerfile: ./frontend/Dockerfile  # Specify the Dockerfile location for frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:C:/app  # Mount frontend code for live editing
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necessary for live-reload in Docker

  exe:
    build:
      context: "C:/Blocks"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Network access for the EXE
    volumes:
      - ./config:C:/Documents/AirSim  # Mount the same settings.json
