name: DroneWorld
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:C:/app  # Mount backend code
      - ./config/settings.json:C:/Documents/AirSim/settings.json  # Mount settings.json for simulation
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:C:/app  # Mount frontend code for live editing
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necessary for live-reload in Docker

  exe:
    build:
      context: "C:/Blocks"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Network access for the EXE
    volumes:
      - ./config:C:/Documents/AirSim  # Mount the same settings.json
